server:
  port: 80
cors:
  originPatterns: http://localhost:8080,http://localhost:3000
spring:
  application:
    name: products-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_products_api}?sslMode=REQUIRED&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false
logging:
  level:
    com.maxzdosreis: DEBUG
spring-doc:
  paths-to-match:
    - /auth/**
    - /api/**
  swagger-ui:
    use-root-path: true